data:
  dataset_url : "./inputs/final/Medications.txt"
  clean_dataset_url : "./inputs/final/medications.txt"

models:
  model_id: "EleutherAI/gpt-neox-20b"
  hf_repo : "laris/hp_repo"
  device : "cuda:0"

